### ISSUE TITLE
ophys tutorial presenting errors

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#685]
## 1) Bug

copy/paste of [this ophys tutorial](https://pynwb.readthedocs.io/en/latest/tutorials/domain/ophys.html#sphx-glr-tutorials-domain-ophys-py) throws the following errors:

```
/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py:762: MissingRequiredWarning: dataset 'manifold' for 'my_imgpln' of type (ImagingPlane)
  warnings.warn(msg, MissingRequiredWarning)
/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py:729: MissingRequiredWarning: attribute 'pmt_gain' for 'test_iS' (TwoPhotonSeries)
  warnings.warn(msg, MissingRequiredWarning)
/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py:729: MissingRequiredWarning: attribute 'scan_line_rate' for 'test_iS' (TwoPhotonSeries)
  warnings.warn(msg, MissingRequiredWarning)
Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 981, in construct
    obj = cls(**kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/ophys.py", line 161, in __init__
    super(TwoPhotonSeries, self).__init__(*pargs, **pkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/image.py", line 70, in __init__
    call_docval_func(super(ImageSeries, self).__init__, kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 268, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/base.py", line 180, in __init__
    raise TypeError("either 'timestamps' or 'rate' must be specified")
TypeError: either 'timestamps' or 'rate' must be specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/test_3d_rois.py", line 179, in <module>
    nwbfile = io.read()
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 190, in construct
    result = self.__type_map.construct(builder, self)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1402, in construct
    return attr_map.construct(builder, build_manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 957, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 899, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 939, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 899, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 931, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 944, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 944, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 190, in construct
    result = self.__type_map.construct(builder, self)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1402, in construct
    return attr_map.construct(builder, build_manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 985, in construct
    raise_from(Exception(msg), ex)
  File "<string>", line 3, in raise_from
Exception: Could not construct TwoPhotonSeries object
```

The issue with 'pmt_gain' is confusing to me. It's listed as optional in the schema and there's a default arg of `None` in the docval, so I don't understand why an error is being thrown.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
@ajtritt can you take a look at this when you have a moment?

**Comment by ajtritt** [comment]
Have you updated recently? I encountered this error myself sometime recently during the table refactorings. The issue is that empty lists don't get written to disk, so there's nothing to pass in to the constructor when it gets read back in. The tutorial should be changed, so updating should fix the exception

https://github.com/NeurodataWithoutBorders/pynwb/blob/ddb64f58807186093b0b3260506e97e6b1a893e7/docs/gallery/domain/ophys.py#L76-L78

I'm not sure why it's issuing a warning over pmt_gain, but it shouldn't keep it from running.

**Comment by bendichter** [comment]
This was after a hard reset to remote dev branch, so I think the issue is still there.

**Comment by t-b** [comment]
@bendichter Works here as well with `ddb64f58 (Merge pull request #681 from NileGraddis/680/hdf5io-accept-files, 2018-10-25)`. IIRC the tutorials are built during CI so we should never have the case that they don't build in dev.

**Comment by bendichter** [comment]
The error was due to the browser cache on my end. Thanks @ajtritt and @t-b. 

I'm going to leave this up because I'd also like to track down the erroneous warnings. It looks like #689 is relevant.
